### ISSUE TITLE
Error setting up entry * for renault

### ISSUE THREAD

**Issue by TheArcturian** [hacf-fr/hassRenaultZE#117]
I've just installed the component, added my correct credentials and restarted HA according to your description. However I get the following error:

```
Logger: homeassistant.config_entries
Source: custom_components/renault/renault_vehicle.py:153
First occurred: 12:42:14 PM (1 occurrences)
Last logged: 12:42:14 PM

Error setting up entry 94f7d039-cd58-4bba-8937-c5f4e09c8781 for renault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renault/__init__.py", line 34, in async_setup_entry
    await renault_hub.async_initialise(config_entry)
  File "/config/custom_components/renault/renault_hub.py", line 70, in async_initialise
    await vehicle.async_initialise()
  File "/config/custom_components/renault/renault_vehicle.py", line 94, in async_initialise
    if await self.endpoint_available("charge-mode"):
  File "/config/custom_components/renault/renault_vehicle.py", line 153, in endpoint_available
    self.details.vin(),
TypeError: 'str' object is not callable
```

I've already activated debug logging. It is a clean install as I haven't used your component before.

Any idea what I can do to make it work?

**Comment by epenet** [comment]
Can you please try branch [fix-endpoint-available](https://github.com/hacf-fr/hassRenaultZE/tree/fix-endpoint-available) and confirm it is working correctly before I merge it into master?

**Comment by TheArcturian** [comment]
That one worked perfect! Thanks!
