### ISSUE TITLE
All Unavailable today

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#141]
All is unavailable today. Renault stop servers?

## Version of the custom_component
 i just bump to 3.0.8 now but it's always down

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by alexanderfitu** [comment]
Yes likewise, logs:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renault/__init__.py", line 33, in async_setup_entry
    await renault_hub.async_initialise(config_entry)
  File "/config/custom_components/renault/renault_hub.py", line 58, in async_initialise
    vehicles = await self._account.get_vehicles()
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_account.py", line 62, in get_vehicles
    return await self.session.get_account_vehicles(
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_session.py", line 188, in get_account_vehicles
    return await kamereon.get_account_vehicles(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 226, in get_account_vehicles
    await request(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 143, in request
    kamereon_response: models.KamereonResponse = schema.loads(response_text)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 760, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by JeedHome44** [comment]
I am reassured.  I thought it came from my connection

**Comment by alexanderfitu** [comment]
Looks like ZE Services is having issues as my app does not work either.

**Comment by JeedHome44** [comment]
again the cleaning lady who unplugged the wire

**Comment by JeedHome44** [comment]
I can restart Hassio! It's ok now for me! 😉
